name: auto-commit-workflow
on: 
  pull_request_review:
jobs:
  approve-bot:
    if: github.event.review.user.login == 'my-test-bot' && github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    name: auto-commit-workflow
    steps:
      - name: Debug logging
        shell: bash
        run: |
          echo '${{ toJSON(github) }}'

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: auto-commit action
        uses: ./.github/actions/auto-commit-action
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
