name: codeowner-workflow
on: 
  pull_request:
    branches:
      - main
jobs:
  correct-timestamps:
    runs-on: ubuntu-latest
    name: Codeowner stuff
    steps:
      - name: Debug logging
        shell: bash
        run: |
          echo '${{ toJSON(github) }}'

      - name: Codeowner action
        uses: ./.github/actions/codeowner-action
